id: ConcentricAI Demo Playbook
version: 15
vcShouldKeepItemLegacyProdMachine: false
name: ConcentricAI Demo Playbook
description: This playbook will show how to handle a risk incident and fetch all appropriate
  file details with respect to it along with user details for the owner of the File.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ed889bf3-8a59-4ba8-8c9d-c88e0dcf437d
    type: start
    task:
      id: ed889bf3-8a59-4ba8-8c9d-c88e0dcf437d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 6423b84a-77d1-46ef-8532-94f484670ecb
    type: regular
    task:
      id: 6423b84a-77d1-46ef-8532-94f484670ecb
      version: -1
      name: get-file-details
      description: Get's file information
      script: '|||ConcentricAI-get-file-details'
      type: regular
      iscommand: true
      brand: ""
    scriptarguments:
      file-name:
        simple: ${incident.filename}
      path:
        simple: ${incident.filepath}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 180,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 0abe895f-7443-4b21-8511-be09344dbd31
    type: regular
    task:
      id: 0abe895f-7443-4b21-8511-be09344dbd31
      version: -1
      name: get-user-details
      description: Get's user details
      script: '|||ConcentricAI-get-user-details'
      type: regular
      iscommand: true
      brand: ""
    scriptarguments:
      user:
        simple: ${incident.agentid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 750,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 295,
        "width": 950,
        "x": 180,
        "y": 170
      }
    }
  }
inputs:
- key: File Name
  value:
    simple: ${incident.filename}
  required: true
  description: File Name to check
  playbookInputQuery: null
- key: Path Name
  value:
    simple: ${incident.filepath}
  required: true
  description: The path of the file.
  playbookInputQuery: null
outputs: []
fromversion: 6.0.0
